-- Create app_changelogs table
create table if not exists public.app_changelogs (
    id bigint generated by default as identity primary key,
    version text not null,
    release_date timestamptz default now(),
    changes jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

-- Enable RLS
alter table public.app_changelogs enable row level security;

-- Create policies
create policy "Allow read access to everyone"
on public.app_changelogs for select
using (true);

create policy "Allow insert/update/delete to service_role only"
on public.app_changelogs for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

-- Create index for version query optimization
create index if not exists app_changelogs_version_idx on public.app_changelogs (version);
create index if not exists app_changelogs_release_date_idx on public.app_changelogs (release_date desc);
